"""Create playlist table

Revision ID: 46c53c1bf72d
Revises: 705e05288723
Create Date: 2023-12-18 16:17:47.525247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c53c1bf72d'
down_revision: Union[str, None] = '705e05288723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'playlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'user_id')
    # ### end Alembic commands ###
