"""Remove user id from songs table

Revision ID: 56a1000f1a2b
Revises: 46c53c1bf72d
Create Date: 2023-12-18 19:56:39.563884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a1000f1a2b'
down_revision: Union[str, None] = '46c53c1bf72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('songs_user_id_fkey', 'songs', type_='foreignkey')
    op.drop_column('songs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('songs_user_id_fkey', 'songs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
