"""corrected typo in song schema

Revision ID: 61e3214cdc9a
Revises: ec79ca84e61f
Create Date: 2023-12-18 21:42:38.461474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e3214cdc9a'
down_revision: Union[str, None] = 'ec79ca84e61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
